import java.util.LinkedList;

/*
 * perhaps randomly, orders will be generated by the Orders part of the simulation. 
 * Each order will have an address and a few desired items. We can think of orders 
 * being in a queue at the picker station. A picker is working on one order at a time. 
 * The Orders part is doing the work of the picker. Orders has to ask Inventory which 
 * shelf has a desired item, then ask Floor where is that shelf, then as Robot to bring 
 * that shelf to the picker location, tell Inventory to remove the item from the shelf, 
 * then tell a robot to take the shelf back to the shelving area. After all items of an 
 * order are collected at the picker station, Orders can tell Belt that a bin is complete. 
 * Orders has to wait for many ticks while a robot is bringing a shelf; Orders might also 
 * have to wait because there is a full bin but the Belt has not moved it yet.
 */
public class Order {
	private int random;
	private Floor floor;
	private Inventory inventory;
	private Item item;
	LinkedList<Item> order_queue = new LinkedList<Item>();
	private Robot robot;
	private boolean order_showup;
	private Point shelf;
	public Order(Inventory inventory, Floor floor) {
		this.inventory = inventory;
		this.floor = floor;
	}
	
	/*
	 * (int)(Math.random() * 20) create chances that might not have orders,
	 * since num is 0-9 inclusive.
	 */
	public int random_number() {
		random = (int)(Math.random() * 20);
		System.out.println("random number is " + random);
		return random;
		
	}
	
	//use random_number method(above) to produce a ramdom order(below)
	public void make_Order() {
		//Item item;
		int rand = random_number();
		if (random > 10) {
			order_showup = false;
			System.out.println("No order comes up yet...");
		}
		if (rand == 0) {
			order_showup = true;
			item = inventory.item_arr[0];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[0].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 1) {
			order_showup = true;
			item = inventory.item_arr[1];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[1].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 2) {
			order_showup = true;
			item = inventory.item_arr[3];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[3].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 3) {
			order_showup = true;
			item = inventory.item_arr[2];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[2].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 4) {
			order_showup = true;
			item = inventory.item_arr[4];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[4].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 5) {
			order_showup = true;
			item = inventory.item_arr[5];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[5].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 6) {
			order_showup = true;
			item = inventory.item_arr[6];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[6].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 7) {
			order_showup = true;
			item = inventory.item_arr[7];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[7].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 8) {
			order_showup = true;
			item = inventory.item_arr[8];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[8].Stock--;
			inventory.stock_Warning();
		}
		else if (rand == 9) {
			order_showup = true;
			item = inventory.item_arr[9];
			shelf = item.place;
			System.out.println("Order is on the shelf " + item.place);
			order_queue.add(item);
			inventory.item_arr[9].Stock--;
			inventory.stock_Warning();
		}
	}
	
	// Robot will use this method to detect which shelf should it go.
	public boolean order_Showup() {
		make_Order();
		return this.order_showup;
	}
	
	public Point find_Shelf() {
		return this.shelf;
	}
}
