/*
 * perhaps randomly, orders will be generated by the Orders part of the simulation. 
 * Each order will have an address and a few desired items. We can think of orders 
 * being in a queue at the picker station. A picker is working on one order at a time. 
 * The Orders part is doing the work of the picker. Orders has to ask Inventory which 
 * shelf has a desired item, then ask Floor where is that shelf, then as Robot to bring 
 * that shelf to the picker location, tell Inventory to remove the item from the shelf, 
 * then tell a robot to take the shelf back to the shelving area. After all items of an 
 * order are collected at the picker station, Orders can tell Belt that a bin is complete. 
 * Orders has to wait for many ticks while a robot is bringing a shelf; Orders might also 
 * have to wait because there is a full bin but the Belt has not moved it yet.
 */
public class Order {
	public Order() {
		
	}
}
